name: my first workflow
on: push
jobs:
  first_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "my first github actions job"
      - name: List all files
        run: ls
      - name: Read all files
        run: cat README.md
