name: Generate ASCII
on: push
jobs:
  ascii-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: List all files
        run: ls -ltra

      - name: Execute Shell Command
        run: |
          chmod +x ascii.sh
          ./ascii.sh
